apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: "deployment-lab"
    version: "blue"
  name: "deployment-lab-dp-blue"
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: "deployment-lab"
      version: "blue"
  minReadySeconds: 5
  progressDeadlineSeconds: 600
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "deployment-lab"
        version: "blue"
    spec:
      containers:
      - image: killuazhu/deployment-lab:blue
        livenessProbe:
          httpGet:
            path: /health
            port: 8090
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 1
        name: deployment-lab
        ports:
        - containerPort: 8090
          protocol: TCP
        # resources:
        #   requests:
        #     cpu: "100m"
        #     memory: "100m"
        #   limits:
        #     cpu: "500m"
        #     memory: "500m"
            
