apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: "deployment-lab"
spec:
  type: NodePort
  ports:
  - name: http
    port: 8090
  selector:
    app: "deployment-lab"
    version: "blue"
